### ISSUE TITLE
more information needed about the solution

### ISSUE THREAD

**Issue by latheefp** [lgchiaretto/openshift4-backup-automation#3]
hello, Thank your support.
please provide below information as part of the docs.
1. the location of the backup , whether in worker node or jumphost?
2. is there a way to increase the count and requency?
3. the cronjob is set in OCP nodes or jumphost?
4. how to test it manually and check and validate it. 
5. how to restore it

**Comment by lgchiaretto** [comment]
Hello, thanks for using this project, and here are the answers.

- the location of the backup , whether in worker node or jumphost?

By default is /home/core/backup on all master nodes

- is there a way to increase the count and frequency?

Yes, just edit this line and change the value of "ctime" from "+2" to another value that you want.

- the cronjob is set in OCP nodes or jumphost?

It's a cronjob on OCP

- how to test it manually and check and validate it

`oc delete job backup --ignore-not-found=true -n ocp-backup-etcd && oc create job backup --from=cronjob.batch/openshift-backup -n ocp-backup-etcd`
 
- how to restore it

https://docs.openshift.com/container-platform/4.8/backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-restoring-cluster-state

**Comment by latheefp** [comment]
Thank you. i am checking this and get back to you.

**Comment by latheefp** [comment]
its working fine. i have edited to work with nfs mount.
