### ISSUE TITLE
Crontjob is running wrong timing 

### ISSUE THREAD

**Issue by latheefp** [lgchiaretto/openshift4-backup-automation#4]
```
[core@jumphost ~]$ oc get CronJob -A
NAMESPACE                              NAME               SCHEDULE       SUSPEND   ACTIVE   LAST SCHEDULE   AGE
ocp-backup-etcd                        openshift-backup   56 23 * * *    False     0        <none>          4m51s
```

I tried to change the time to current time, still it did not run or i cannot the output in any master node.

```
[core@jumphost ~]$ oc get CronJob -A
NAMESPACE                              NAME               SCHEDULE       SUSPEND   ACTIVE   LAST SCHEDULE   AGE
ocp-backup-etcd                        openshift-backup   11 3 * * *     False     0        <none>          54m
openshift-image-registry               image-pruner       0 0 * * *      False     0        8h              3d18h
openshift-operator-lifecycle-manager   collect-profiles   */15 * * * *   False     0        14m             3d18h
[core@jumphost ~]$ date
Thu Dec  2 11:29:44 +03 2021
```

**Comment by latheefp** [comment]
`[core@jumphost ~]$ oc get events
LAST SEEN   TYPE      REASON                 OBJECT                MESSAGE
63m         Normal    Scheduled              pod/backup--1-9vvj2   Successfully assigned ocp-backup-etcd/backup--1-9vvj2 to worker12.esb-pp.prod.mobily.lan
63m         Normal    AddedInterface         pod/backup--1-9vvj2   Add eth0 [192.168.24.8/23] from openshift-sdn
63m         Normal    Pulling                pod/backup--1-9vvj2   Pulling image "registry.redhat.io/openshift4/ose-cli:v4.8"
62m         Normal    Pulled                 pod/backup--1-9vvj2   Successfully pulled image "registry.redhat.io/openshift4/ose-cli:v4.8" in 29.986415606s
62m         Normal    Created                pod/backup--1-9vvj2   Created container backup
62m         Normal    Started                pod/backup--1-9vvj2   Started container backup
62m         Warning   FailedMount            pod/backup--1-9vvj2   MountVolume.SetUp failed for volume "kube-api-access-fsq42" : [object "ocp-backup-etcd"/"kube-root-ca.crt" not registered, object "ocp-backup-etcd"/"openshift-service-ca.crt" not registered]
63m         Normal    SuccessfulCreate       job/backup            Created pod: backup--1-9vvj2
62m         Warning   BackoffLimitExceeded   job/backup            Job has reached the specified backoff limit
`

**Comment by latheefp** [comment]
```
[core@jumphost ~]$ oc get events
LAST SEEN   TYPE      REASON                 OBJECT                MESSAGE
63m         Normal    Scheduled              pod/backup--1-9vvj2   Successfully assigned ocp-backup-etcd/backup--1-9vvj2 to worker12.esb-pp.prod.mobily.lan
63m         Normal    AddedInterface         pod/backup--1-9vvj2   Add eth0 [192.168.24.8/23] from openshift-sdn
63m         Normal    Pulling                pod/backup--1-9vvj2   Pulling image "registry.redhat.io/openshift4/ose-cli:v4.8"
62m         Normal    Pulled                 pod/backup--1-9vvj2   Successfully pulled image "registry.redhat.io/openshift4/ose-cli:v4.8" in 29.986415606s
62m         Normal    Created                pod/backup--1-9vvj2   Created container backup
62m         Normal    Started                pod/backup--1-9vvj2   Started container backup
62m         Warning   FailedMount            pod/backup--1-9vvj2   MountVolume.SetUp failed for volume "kube-api-access-fsq42" : [object "ocp-backup-etcd"/"kube-root-ca.crt" not registered, object "ocp-backup-etcd"/"openshift-service-ca.crt" not registered]
63m         Normal    SuccessfulCreate       job/backup            Created pod: backup--1-9vvj2
62m         Warning   BackoffLimitExceeded   job/backup            Job has reached the specified backoff limit
```

**Comment by latheefp** [comment]
`
[core@jumphost ~]$ oc get  pod/backup--1-9vvj2 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "192.168.24.8"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "192.168.24.8"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted
  creationTimestamp: "2021-12-02T07:41:16Z"
  generateName: backup--1-
  labels:
    app: openshift-backup
    controller-uid: d85044b7-fff6-482e-a2a8-7eb3615c6984
    job-name: backup
  name: backup--1-9vvj2
  namespace: ocp-backup-etcd
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: backup
    uid: d85044b7-fff6-482e-a2a8-7eb3615c6984
  resourceVersion: "2027918"
  uid: b0b35bf3-d05f-4e1d-9b8e-73edc3d8ed3d
spec:
  activeDeadlineSeconds: 600
  containers:
  - command:
    - /bin/bash
    - -c
    - oc get no -l node-role.kubernetes.io/master --no-headers -o name | xargs -I
      {} --  oc debug {} -- bash -c 'chroot /host sudo -E /usr/local/bin/cluster-backup.sh
      /home/core/backup/ && chroot /host sudo -E find /home/core/backup/ -type f -ctime
      +"2" -delete'
    image: registry.redhat.io/openshift4/ose-cli:v4.8
    imagePullPolicy: IfNotPresent
    name: backup
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000660000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fsq42
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: openshift-backup-dockercfg-nqffg
  nodeName: worker12.esb-pp.prod.mobily.lan
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000660000
    seLinuxOptions:
      level: s0:c26,c5
  serviceAccount: openshift-backup
  serviceAccountName: openshift-backup
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-fsq42
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-02T07:41:16Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-12-02T07:41:50Z"
    message: 'containers with unready status: [backup]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-12-02T07:41:50Z"
    message: 'containers with unready status: [backup]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-12-02T07:41:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://5637a5725ba4fa4d46d01db9c8a3c814ebc392190799e65fb53896be20dc1ab9
    image: registry.redhat.io/openshift4/ose-cli:v4.8
    imageID: registry.redhat.io/openshift4/ose-cli@sha256:14aa7a76f70357de44414af03adc98d41ab7f269f2308ca524660e16626a5652
    lastState: {}
    name: backup
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://5637a5725ba4fa4d46d01db9c8a3c814ebc392190799e65fb53896be20dc1ab9
        exitCode: 123
        finishedAt: "2021-12-02T07:41:49Z"
        reason: Error
        startedAt: "2021-12-02T07:41:48Z"
  hostIP: 10.14.172.132
  phase: Failed
  podIP: 192.168.24.8
  podIPs:
  - ip: 192.168.24.8
  qosClass: BestEffort
  startTime: "2021-12-02T07:41:16Z"

`

**Comment by latheefp** [comment]
```
[core@jumphost ~]$ oc get  pod/backup--1-9vvj2 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "192.168.24.8"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "192.168.24.8"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted
  creationTimestamp: "2021-12-02T07:41:16Z"
  generateName: backup--1-
  labels:
    app: openshift-backup
    controller-uid: d85044b7-fff6-482e-a2a8-7eb3615c6984
    job-name: backup
  name: backup--1-9vvj2
  namespace: ocp-backup-etcd
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: backup
    uid: d85044b7-fff6-482e-a2a8-7eb3615c6984
  resourceVersion: "2027918"
  uid: b0b35bf3-d05f-4e1d-9b8e-73edc3d8ed3d
spec:
  activeDeadlineSeconds: 600
  containers:
  - command:
    - /bin/bash
    - -c
    - oc get no -l node-role.kubernetes.io/master --no-headers -o name | xargs -I
      {} --  oc debug {} -- bash -c 'chroot /host sudo -E /usr/local/bin/cluster-backup.sh
      /home/core/backup/ && chroot /host sudo -E find /home/core/backup/ -type f -ctime
      +"2" -delete'
    image: registry.redhat.io/openshift4/ose-cli:v4.8
    imagePullPolicy: IfNotPresent
    name: backup
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000660000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fsq42
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: openshift-backup-dockercfg-nqffg
  nodeName: worker12.esb-pp.prod.mobily.lan
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000660000
    seLinuxOptions:
      level: s0:c26,c5
  serviceAccount: openshift-backup
  serviceAccountName: openshift-backup
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-fsq42
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-02T07:41:16Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-12-02T07:41:50Z"
    message: 'containers with unready status: [backup]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-12-02T07:41:50Z"
    message: 'containers with unready status: [backup]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-12-02T07:41:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://5637a5725ba4fa4d46d01db9c8a3c814ebc392190799e65fb53896be20dc1ab9
    image: registry.redhat.io/openshift4/ose-cli:v4.8
    imageID: registry.redhat.io/openshift4/ose-cli@sha256:14aa7a76f70357de44414af03adc98d41ab7f269f2308ca524660e16626a5652
    lastState: {}
    name: backup
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://5637a5725ba4fa4d46d01db9c8a3c814ebc392190799e65fb53896be20dc1ab9
        exitCode: 123
        finishedAt: "2021-12-02T07:41:49Z"
        reason: Error
        startedAt: "2021-12-02T07:41:48Z"
  hostIP: 10.14.172.132
  phase: Failed
  podIP: 192.168.24.8
  podIPs:
  - ip: 192.168.24.8
  qosClass: BestEffort
  startTime: "2021-12-02T07:41:16Z"

```

**Comment by lgchiaretto** [comment]
Hello @latheefp,

by default, all Cronjob runs over **UTC** timezone on Openshift.

**Comment by lgchiaretto** [comment]
@latheefp which OCP version are you running the Backup Automation Tool?

**Comment by latheefp** [comment]
its 4.8
