### ISSUE TITLE
How to copy files from master host to S3 bucket 

### ISSUE THREAD

**Issue by Niha2410** [lgchiaretto/openshift4-backup-automation#5]
What is the procedure to copy files from master host to S3 bucket as I have an issue copying the files from master host to S3 bucket from Cronjob.

**Comment by lgchiaretto** [comment]
Hi, @Niha2410,

I did not implement this functionality on OCP Backup Automation because Openshift is agnostic from infrastructure. So you can run Openshift on AWS or VMware or Azure and so on. I really think it's not a good idea to copy the file outside the master.

Please, read this answer to understand why.

https://access.redhat.com/discussions/4972611#comment-2088241

**Comment by latheefp** [comment]
I did few changes to move the backup to nfs moutpoint. jumphost is the nfs servers in my configuration. this is working fine. you can edit the command with required changes to move the backup to target location.  
`apiVersion: v1
items:
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{},"labels":{"app":"openshift-backup"},"name":"openshift-backup","namespace":"ocp-backup-etcd"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":5,"jobTemplate":{"metadata":{"labels":{"app":"openshift-backup"}},"spec":{"backoffLimit":0,"template":{"metadata":{"labels":{"app":"openshift-backup"}},"spec":{"activeDeadlineSeconds":600,"containers":[{"command":["/bin/bash","-c","oc get no -l node-role.kubernetes.io/master --no-headers -o name | xargs -I {} -- oc debug {} -- bash -c 'chroot /host mkdir   /home/core/backup \u0026\u0026 chroot /host sudo -E sudo mount -t nfs -o vers=4 jumphost.mwave-pp.prod.mobily.lan:/ocp/etcd-backup /home/core/backup \u0026\u0026 chroot /host sudo -E /usr/local/bin/cluster-backup.sh /home/core/backup/ \u0026\u0026 chroot /host sudo -E find /home/core/backup/ -type f -mtime +\"30\" -delete \u0026\u0026 chroot /host sudo -E sudo umount /home/core/backup'"],"image":"registry.redhat.io/openshift4/ose-cli:v4.8","name":"backup"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Never","serviceAccount":"openshift-backup","serviceAccountName":"openshift-backup","terminationGracePeriodSeconds":30}}}},"schedule":"56 23 * * *","successfulJobsHistoryLimit":5}}
    creationTimestamp: "2021-12-21T07:17:48Z"
    generation: 4
    labels:
      app: openshift-backup
    name: openshift-backup
    namespace: ocp-backup-etcd
    resourceVersion: "424524"
    uid: 6498f6a8-fa71-4318-a4ff-766a18145839
  spec:
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 5
    jobTemplate:
      metadata:
        creationTimestamp: null
        labels:
          app: openshift-backup
      spec:
        backoffLimit: 0
        template:
          metadata:
            creationTimestamp: null
            labels:
              app: openshift-backup
          spec:
            activeDeadlineSeconds: 600
            containers:
            - command:
              - /bin/bash
              - -c
              - oc get no -l node-role.kubernetes.io/master --no-headers -o name |
                xargs -I {} -- oc debug {} -- bash -c 'chroot /host [ -d /home/core/backup
                ] || mkdir /home/core/backup && chroot /host sudo -E sudo mount -t
                nfs -o vers=4 jumphost:/ocp/etcd-backup /home/core/backup
                && chroot /host sudo -E /usr/local/bin/cluster-backup.sh /home/core/backup/
                && chroot /host sudo -E find /home/core/backup/ -type f -mtime +"30"
                -delete && chroot /host sudo -E sudo umount /home/core/backup'
              image: registry.redhat.io/openshift4/ose-cli:v4.8
              imagePullPolicy: IfNotPresent
              name: backup
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext: {}
            serviceAccount: openshift-backup
            serviceAccountName: openshift-backup
            terminationGracePeriodSeconds: 30
    schedule: 56 23 * * *
    successfulJobsHistoryLimit: 5
    suspend: false
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""`
