### ISSUE TITLE
CronJob is deprecated in v1.21+, unavailable in v1.25

### ISSUE THREAD

**Issue by latheefp** [lgchiaretto/openshift4-backup-automation#6]
I am installing it again. getting the deprecated message. hope you will be fixing it soon. 

**`root@RY-LP-220657M:/mnt/h/openshift/backup# oc apply -f openshift4-backup.yaml
Warning: resource namespaces/ocp-backup-etcd is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
namespace/ocp-backup-etcd configured
serviceaccount/openshift-backup created
clusterrole.rbac.authorization.k8s.io/cluster-etcd-backup unchanged
clusterrolebinding.rbac.authorization.k8s.io/openshift-backup unchanged
W1219 14:52:44.164713    2084 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W1219 14:52:44.250123    2084 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
cronjob.batch/openshift-backup created
root@RY-LP-220657M:/mnt/h/openshift/backup#`**

**Comment by lgchiaretto** [comment]
Hello @latheefp 

Thanks for this issue. The API has been changed!
